import type { GuestLanguage } from '@/lib/guest-languages';

// Columns: Korean, English, Japanese, simplified Chinese.
const messages = {
  home: ['홈', 'Home', 'ホーム', '首页'],
  guide: ['숙소 안내', 'Guide', '宿泊案内', '住宿指南'],
  services: ['서비스', 'Requests', 'サービス', '服务'],
  myRequests: ['내 신청', 'My requests', '申込履歴', '我的申请'],
  welcome: ['편안하게 머물러 주세요.', 'Make yourself at home.', 'どうぞ、ごゆっくり。', '自在入住，安心休息。'],
  welcomeSub: ['머무는 동안 필요한 모든 것을 가까이.', 'A little help for a lovely stay.', '滞在に必要なことを、すぐ手元に。', '入住期间所需，尽在手边。'],
  language: ['언어', 'Language', '言語', '语言'],
  preview: ['미리보기', 'Preview', 'プレビュー', '预览'],
  previewNote: ['예시 예약입니다. 신청은 이 화면에만 저장됩니다.', 'Sample stay. Requests are saved on this screen only.', 'サンプル予約です。お申し込みはこの画面内にのみ保存されます。', '示例预订。申请仅保存在当前页面。'],
  login: ['내 예약 확인', 'Find your stay', '予約を確認', '确认我的预订'],
  loginIntro: ['예약자 이름과 숙소에서 보내드린 이용 코드를 입력해 주세요.', 'Enter your reservation name and the access code sent by your host.', '予約者名と宿泊施設から届いた利用コードを入力してください。', '请输入预订姓名及住宿方发来的使用代码。'],
  qrIntro: ['예약 전용 초대장입니다. 예약에 사용한 이름을 입력해 주세요.', 'Your personal invitation is ready. Enter the name used for your reservation.', '予約専用の招待状です。予約時のお名前を入力してください。', '这是您的专属邀请。请输入预订时使用的姓名。'],
  name: ['예약자 이름', 'Reservation name', '予約者名', '预订姓名'],
  code: ['숙소 이용 코드', 'Stay access code', '宿泊利用コード', '住宿使用代码'],
  codeHint: ['숙소에서 보낸 예약 안내 메시지에서 확인할 수 있습니다.', 'Find this code in your host’s reservation message.', '宿泊施設からの予約案内メッセージをご確認ください。', '请在住宿方发送的预订消息中查看。'],
  enter: ['게스트 라운지 입장', 'Enter guest lounge', 'ゲストラウンジへ', '进入住客服务'],
  noCode: ['코드가 없으면 예약한 플랫폼의 메시지로 숙소에 문의해 주세요.', 'No code? Contact your host through your original booking channel.', 'コードがない場合は、ご予約のプラットフォームからお問い合わせください。', '没有代码？请通过原预订平台联系住宿方。'],
  loading: ['불러오는 중…', 'Loading…', '読み込み中…', '加载中…'],
  retry: ['다시 시도', 'Try again', '再試行', '重试'],
  error: ['정보를 불러오지 못했습니다. 다시 시도해 주세요.', 'We couldn’t load this. Please try again.', '情報を読み込めませんでした。再度お試しください。', '无法加载信息，请重试。'],
  loginError: ['예약을 확인하지 못했습니다. 예약자 이름과 이용 코드를 확인해 주세요.', 'We couldn’t verify this stay. Check the reservation name and access code.', '予約を確認できませんでした。お名前とコードをご確認ください。', '无法确认预订，请检查姓名及使用代码。'],
  expired: ['이용 시간이 종료되었습니다. 예약 정보를 확인하고 다시 접속해 주세요.', 'Your access has ended. Check your stay details to sign in again.', '利用期限が終了しました。予約情報を確認して再度ログインしてください。', '使用期限已结束，请确认预订信息并重新登录。'],
  rateError: ['잠시 기다린 후 다시 시도해 주세요.', 'Please wait a moment before trying again.', '少しお待ちいただき、再度お試しください。', '请稍等后再试。'],
  connectionError: ['연결하지 못했습니다. 입력 내용은 유지됩니다. 다시 시도해 주세요.', 'Connection unavailable. Your entries are still here. Please try again.', '接続できませんでした。入力内容は保持されています。再度お試しください。', '暂时无法连接，已保留填写内容，请重试。'],
  inputError: ['날짜, 시간과 입력 내용을 확인해 주세요. 신청 시간은 현재보다 이후여야 합니다.', 'Please check the date, time and request details. Your requested time must be in the future.', '日付、時間、入力内容をご確認ください。現在より後の時間を選択してください。', '请检查日期、时间和申请内容，所选时间必须晚于当前时间。'],
  refreshNeeded: ['예약 연결을 다시 확인해 주세요. 입력 내용은 유지됩니다.', 'Please check your stay connection again. Your entries are still here.', '予約の接続を再確認してください。入力内容は保持されています。', '请重新确认预订连接，已保留填写内容。'],
  useCode: ['이용 코드로 확인하기', 'Use an access code instead', '利用コードで確認する', '使用代码确认'],
  helpAfterCheckin: ['비품 요청과 불편사항 문의는 체크인 후 이용할 수 있습니다. 도착 전 문의는 예약 플랫폼으로 보내주세요.', 'Room assistance is available after check-in. For questions before arrival, contact your host through your booking channel.', '備品の依頼や客室のお問い合わせはチェックイン後にご利用いただけます。到着前は予約プラットフォームからお問い合わせください。', '客房物品及问题申请在入住后提供，抵达前请通过原预订平台联系住宿方。'],
  logout: ['로그아웃', 'Sign out', 'ログアウト', '退出登录'],
  checkin: ['체크인', 'Check-in', 'チェックイン', '入住'],
  checkout: ['체크아웃', 'Check-out', 'チェックアウト', '退房'],
  guests: ['명', 'guests', '名', '人'],
  nights: ['박', 'nights', '泊', '晚'],
  beforeArrival: ['여행을 준비하는 시간', 'Before your arrival', '到着前', '入住前'],
  staying: ['머무는 중', 'Enjoy your stay', 'ご滞在中', '入住中'],
  roomGuide: ['숙소 이용 안내', 'Stay essentials', '宿泊施設の利用案内', '住宿使用指南'],
  roomGuideSub: ['와이파이부터 시설 이용법까지.', 'Wi-Fi, house guide and practical tips.', 'Wi-Fiや設備の使い方をご案内。', 'Wi-Fi及设施使用说明。'],
  tours: ['투어·체험', 'Tours & experiences', 'ツアー・体験', '游览与体验'],
  tourSub: ['우리 동네에서 특별한 경험을.', 'A little inspiration for your day.', '街で特別な体験を。', '发现当地的特别体验。'],
  tourCatalogIntro: ['마음에 드는 프로그램을 선택해 코스와 요금을 확인하세요.', 'Choose a programme to explore its courses and prices.', 'プログラムを選び、コースと料金をご確認ください。', '选择喜欢的项目，查看课程与价格。'],
  allTours: ['전체 프로그램', 'All programmes', 'すべてのプログラム', '全部项目'],
  viewProgram: ['프로그램 보기 · 신청', 'View programme & request', '詳細・申し込み', '查看项目并申请'],
  taxi: ['택시 요청', 'Request a taxi', 'タクシーを依頼', '申请出租车'],
  taxiSub: ['이동할 시간과 목적지를 알려주세요.', 'Tell us when and where you’d like to go.', '出発時間と目的地をお知らせください。', '请告知出发时间与目的地。'],
  help: ['숙소에 문의', 'Ask your host', '宿泊施設へ問い合わせ', '联系住宿方'],
  helpSub: ['필요한 비품, 질문, 불편한 점을 알려주세요.', 'Supplies, questions or something to fix.', '備品、ご質問、お困りごと。', '物品需求、问题或使用不便。'],
  address: ['오시는 길', 'Find your way', 'アクセス', '如何到达'],
  map: ['지도 보기', 'Open map', '地図を見る', '查看地图'],
  wifi: ['와이파이', 'Wi-Fi', 'Wi-Fi', 'Wi-Fi'],
  wifiName: ['네트워크', 'Network', 'ネットワーク', '网络名称'],
  wifiPassword: ['비밀번호', 'Password', 'パスワード', '密码'],
  copy: ['복사', 'Copy', 'コピー', '复制'],
  copied: ['복사했습니다', 'Copied', 'コピーしました', '已复制'],
  generalGuide: ['도착 안내', 'Arrival guide', '到着案内', '到达指南'],
  localGuide: ['주변 가이드', 'Neighbourhood guide', '周辺ガイド', '周边指南'],
  events: ['종로 행사', 'Jongno events', '鍾路のイベント', '钟路活动'],
  guideIntro: ['편안한 머무름을 위한 이용 안내입니다.', 'Useful information for a comfortable stay.', '快適な滞在のためのご案内です。', '为舒适入住准备的实用信息。'],
  guidePrivate: ['예약 확인 후 상세 이용 안내와 와이파이를 볼 수 있습니다.', 'Sign in to view your room guide and Wi-Fi.', '予約確認後、詳しい利用案内とWi-Fiをご覧いただけます。', '确认预订后可查看详细指南与Wi-Fi。'],
  prearrivalGuide: ['객실 이용 안내와 와이파이는 체크인 시간부터 제공됩니다.', 'Your room guide and Wi-Fi are available from check-in time.', '客室案内とWi-Fiはチェックイン時間からご利用いただけます。', '客房指南与Wi-Fi从入住时间起提供。'],
  noRoomGuide: ['상세 이용 안내가 준비되면 여기에 표시됩니다.', 'Your detailed room guide will appear here when available.', '詳しい利用案内は準備ができ次第表示されます。', '详细指南准备好后将显示在此处。'],
  bookChannel: ['급한 도움이 필요하면 예약한 플랫폼의 메시지로 숙소에 연락해 주세요.', 'For urgent help, contact your host through your original booking channel.', 'お急ぎの場合は、ご予約のプラットフォームから宿泊施設へご連絡ください。', '如需紧急帮助，请通过原预订平台联系住宿方。'],
  requestIntro: ['간편하게 요청하고 진행 상황을 확인하세요.', 'Send a request and follow its progress here.', '簡単に申し込み、進捗を確認できます。', '轻松申请并查看处理进度。'],
  requestNote: ['신청만으로 예약이 확정되지 않습니다. 담당자가 가능 여부와 요금을 확인한 후 안내드립니다.', 'A request is not a confirmed booking. Your host will review availability and any fare before confirming.', 'お申し込みだけでは予約は確定しません。担当者が空き状況と料金を確認してご案内します。', '提交申请不代表预订确认，住宿方将确认可用情况及费用后通知。'],
  date: ['날짜 (한국 시간)', 'Date (Korea time)', '日付（韓国時間）', '日期（韩国时间）'],
  time: ['시간 (한국 시간)', 'Time (Korea time)', '時間（韓国時間）', '时间（韩国时间）'],
  people: ['인원', 'People', '人数', '人数'],
  bags: ['수하물 개수', 'Pieces of luggage', '荷物の個数', '行李件数'],
  destination: ['목적지', 'Destination', '目的地', '目的地'],
  destinationHint: ['주소, 역 이름 또는 공항 터미널', 'Address, station or airport terminal', '住所、駅名、空港ターミナル', '地址、车站或机场航站楼'],
  note: ['추가 요청사항 (선택)', 'Additional details (optional)', '追加のご要望（任意）', '其他需求（选填）'],
  submit: ['신청 보내기', 'Send request', '申し込む', '提交申请'],
  submitting: ['접수 중…', 'Sending…', '送信中…', '提交中…'],
  received: ['신청을 접수했습니다. 내 신청에서 진행 상황을 확인하세요.', 'Your request is in. Follow it in My requests.', '受け付けました。申込履歴で進捗をご確認ください。', '已收到申请，请在我的申请中查看进度。'],
  previewReceived: ['예시 신청을 추가했습니다. 실제로 전달되지 않습니다.', 'Sample request added. Nothing was sent to your host.', 'サンプルを追加しました。実際には送信されません。', '已添加示例申请，未实际发送。'],
  back: ['뒤로', 'Back', '戻る', '返回'],
  chooseTour: ['체험 선택', 'Choose an experience', '体験を選択', '选择体验'],
  course: ['코스', 'Course', 'コース', '课程'],
  minutes: ['분', 'min', '分', '分钟'],
  priceConfirm: ['최종 금액은 담당자가 확인 후 안내합니다.', 'Your host confirms the final price.', '最終料金は担当者が確認してご案内します。', '最终费用将由住宿方确认。'],
  tierPrice: ['등록된 티켓 요금', 'Published ticket prices', '登録されたチケット料金', '已登记票价'],
  seeDetail: ['체험 자세히 보기', 'View experience details', '体験の詳細を見る', '查看体验详情'],
  noTours: ['지금 신청할 수 있는 체험이 없습니다.', 'There are no experiences available right now.', '現在申し込み可能な体験はありません。', '目前暂无可申请的体验。'],
  category: ['문의 종류', 'How can we help?', 'お問い合わせの種類', '问题类型'],
  supplies: ['비품 요청', 'Supplies', '備品の依頼', '物品申请'],
  issue: ['불편사항', 'Something to fix', 'お困りごと', '使用不便'],
  other: ['기타 문의', 'Other question', 'その他', '其他问题'],
  message: ['필요한 내용을 알려주세요', 'Tell us what you need', 'ご希望をお知らせください', '请描述您的需求'],
  messageHint: ['예: 수건 2장 부탁드립니다. 에어컨에서 찬 바람이 나오지 않습니다.', 'For example: two towels, or the air conditioner is not cooling.', '例：タオル2枚をお願いします。エアコンが冷えません。', '例如：请提供两条毛巾，或空调不制冷。'],
  consent: ['신청 처리에 필요한 정보 이용에 동의합니다.', 'I agree to use these details to handle this request.', 'お申し込みの対応に必要な情報の利用に同意します。', '我同意使用这些信息处理本次申请。'],
  noRequests: ['신청 내역이 여기에 모입니다.', 'Your requests will appear here.', '申込履歴がここに表示されます。', '您的申请将显示在这里。'],
  noRequestsSub: ['객실 패드와 휴대폰에서 보낸 이 예약의 신청을 함께 확인할 수 있습니다.', 'Requests from the room pad and this phone are collected here for your stay.', '客室パッドと携帯電話からの同じ予約のお申し込みを確認できます。', '可统一查看本次预订通过客房平板及手机提交的申请。'],
  refresh: ['새로고침', 'Refresh', '更新', '刷新'],
  hostReply: ['숙소의 안내', 'From your host', '宿泊施設からの案内', '住宿方回复'],
  requested: ['접수됨', 'Received', '受付済', '已接收'],
  reviewing: ['확인 중', 'Under review', '確認中', '确认中'],
  confirmed: ['확정', 'Confirmed', '確定', '已确认'],
  completed: ['완료', 'Completed', '完了', '已完成'],
  cancelled: ['취소', 'Cancelled', 'キャンセル', '已取消'],
  privacy: ['본인 예약과 연결된 신청만 표시됩니다.', 'Only requests for your verified stay are shown.', '確認済みのご予約に紐づくお申し込みのみ表示します。', '仅显示与您已确认预订相关的申请。'],
  allTimes: ['모든 날짜와 시간은 한국 시간(KST) 기준입니다.', 'All dates and times are in Korea time (KST).', '日時はすべて韓国時間（KST）です。', '日期与时间均为韩国时间（KST）。'],
  sampleGuest: ['김민수', 'Alex', '田中', '李明'],
  sampleReply: ['택시를 확인했습니다. 요청하신 시간에 숙소 입구에서 기다려 주세요.', 'Your taxi is confirmed. Please wait at the entrance at the requested time.', 'タクシーを確認しました。ご希望の時間に入口でお待ちください。', '出租车已确认，请按申请时间在入口等候。'],
  sampleTour: ['북촌한지스튜디오', 'Bukchon Hanji Studio', '北村韓紙スタジオ', '北村韩纸工作室'],
  sampleTourDescription: ['전통 한옥에서 한지의 질감과 색을 느끼며 나만의 작품을 만들어 보세요.', 'A hands-on paper craft experience in a traditional hanok.', '伝統韓屋で韓紙の質感と色を楽しみ、作品を作りましょう。', '在传统韩屋中感受韩纸质感与色彩，制作自己的作品。'],
  sampleCourse: ['입문 코스', 'Introductory course', '入門コース', '入门课程'],
  sampleHelp: ['수건 2장 추가로 부탁드립니다.', 'Two additional towels, please.', 'タオルを2枚追加でお願いします。', '请再提供两条毛巾。'],
  loginToRequest: ['예약 확인하고 신청하기', 'Sign in to send requests', '予約を確認して申し込む', '确认预订后申请'],
  airport: ['공항으로 이동', 'To the airport', '空港へ', '前往机场'],
  localTaxi: ['일반 이동', 'Local journey', '市内移動', '市内行程'],
  airportHint: ['공항 이름과 터미널을 입력해 주세요. 출발지는 숙소입니다.', 'Include the airport and terminal. Pickup is from your accommodation.', '空港名とターミナルを入力してください。出発地は宿泊施設です。', '请输入机场与航站楼，出发地为住宿地点。'],
  platform: ['객실 패드에서 신청', 'From the room pad', '客室パッドから', '来自客房平板'],
  noWifi: ['와이파이 정보는 숙소에 문의해 주세요.', 'Ask your host for Wi-Fi details.', 'Wi-Fi情報は宿泊施設へお問い合わせください。', '请向住宿方询问Wi-Fi信息。'],
} as const;
export type GuestStayCopy = { [K in keyof typeof messages]: string };
export function guestStayTranslation(language: GuestLanguage): GuestStayCopy {
  const index = { ko: 0, en: 1, ja: 2, zh: 3 }[language];
  return Object.fromEntries(Object.entries(messages).map(([key, values]) => [key, values[index]])) as GuestStayCopy;
}
