'use client';
import { useState } from 'react';
import Link from 'next/link';
import { confirmDialog } from '@/components/ui';
import { api, field, button, roles, statuses, type Staff, type Property, type Role, type Scope } from './types';

export default function StaffDetail({ staff, properties, selfId, onSaved, onClose }: { staff: Staff; properties: Property[]; selfId?: string; onSaved: () => void; onClose: () => void }) {
  const [tab, setTab] = useState('basic'); const [name, setName] = useState(staff.name); const [phone, setPhone] = useState(staff.phone); const [email, setEmail] = useState(staff.email);
  const [role, setRole] = useState(staff.role); const [mode, setMode] = useState<Scope>(staff.scope); const [ids, setIds] = useState(staff.propertyIds);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [password, setPassword] = useState(''); const [visible, setVisible] = useState(false);
  const [inviteEmail, setInviteEmail] = useState(''); const [inviteToken, setInviteToken] = useState('');
  const cleaner = !!staff.cleanerId; const isSelf = staff.userId === selfId;
  async function action(work: () => Promise<unknown>) { if (busy) return; setBusy(true); setError(''); setMessage(''); try { await work(); setMessage('저장했습니다.'); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : '처리하지 못했습니다.'); } finally { setBusy(false); } }
  const cleanerUpdate = (data: unknown) => api('/api/cleaners', 'PUT', { id: staff.cleanerId, ...(data as object) });
  async function resetLogin() {
    if (!await confirmDialog({ title: staff.userId ? '비밀번호 재발급' : '앱 로그인 만들기', message: staff.userId ? '새 초기 비밀번호를 발급합니다. 기존 비밀번호는 사용할 수 없습니다.' : '이 직원에게 전화번호로 로그인할 수 있는 계정을 만듭니다.', confirmLabel: '발급' })) return;
    await action(async () => { const result = await api(`/api/cleaners/${staff.cleanerId}/reset-password`, 'POST'); setPassword(result.initialPassword); });
  }
  return <section className="border border-stone-300 bg-white p-5 sm:p-7" aria-label={`${staff.name} 직원 상세`}>
    <div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-medium">{staff.name}</h2><p className="mt-2 text-sm text-stone-500">{roles[staff.role]} · {statuses[staff.status] || staff.status}</p></div><button onClick={onClose} type="button" disabled={busy} className={button}>닫기</button></div>
    <div role="group" aria-label="직원 상세 항목" className="my-6 flex flex-wrap gap-2">{[['basic', '기본 정보'], ['properties', '담당 숙소'], ['login', '로그인'], ['notifications', '알림']].map(([value, label]) => <button key={value} type="button" disabled={busy} aria-pressed={tab === value} onClick={() => { setTab(value); setMessage(''); }} className={`${button} ${tab === value ? 'bg-stone-900 text-white' : ''}`}>{label}</button>)}</div>
    <fieldset disabled={busy} className="space-y-5">
      {staff.role === 'cleaner' && !cleaner ? <p className="text-sm text-amber-800">청소 프로필과 연결되지 않은 계정입니다. 기존 청소 이력과 계정 연결을 먼저 확인해야 합니다.</p> : tab === 'basic' && <form className="space-y-5" onSubmit={event => { event.preventDefault(); void action(() => cleaner ? cleanerUpdate({ name, phone }) : api('/api/users', 'PUT', { id: staff.userId, displayName: name, phone, ...(!isSelf ? { email, role } : {}) })); }}>
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">이름<input required maxLength={100} value={name} onChange={event => setName(event.target.value)} className={field} /></label><label className="text-sm">휴대폰<input type="tel" maxLength={40} value={phone} onChange={event => setPhone(event.target.value)} className={field} /></label></div>
        {!cleaner && <><label className="block text-sm">로그인 이메일<input required type="email" disabled={isSelf} value={email} onChange={event => setEmail(event.target.value)} className={field} /></label><label className="block text-sm">역할<select disabled={isSelf || staff.role === 'cleaner'} value={role} onChange={event => setRole(event.target.value as Role)} className={field}>{(staff.role === 'cleaner' ? ['cleaner'] : ['admin', 'manager']).map(value => <option key={value} value={value}>{roles[value as Role]}</option>)}</select></label></>}
        <p className="text-xs text-stone-500">{cleaner ? '이름과 연락처는 연결된 로그인 계정에도 반영됩니다. 연락처 변경으로 비밀번호가 바뀌지는 않습니다.' : '역할과 연락처 변경은 저장 후 적용됩니다.'}</p><button className={`${button} bg-[var(--brand)] text-white`}>기본 정보 저장</button>
      </form>}
      {tab === 'properties' && <form className="space-y-5" onSubmit={event => { event.preventDefault(); void action(() => cleaner ? api(`/api/cleaners/${staff.cleanerId}/properties`, 'PUT', { mode, propertyIds: ids }) : api('/api/users', 'PUT', { id: staff.userId, propertyIds: mode === 'none' ? [] : ids })); }}>
        {staff.role === 'admin' && !cleaner ? <p className="text-sm">관리자는 전체 숙소를 관리합니다.</p> : <><label className="block text-sm">배정 범위<select value={mode} disabled={isSelf && !cleaner} onChange={event => setMode(event.target.value as Scope)} className={field}><option value="none">배정 없음</option><option value="selected">선택한 숙소</option>{cleaner && <option value="all">소유 운영자의 전체 숙소</option>}</select></label>
          {mode === 'selected' && <div className="space-y-3">{properties.map(p => <label key={p.id} className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={isSelf && !cleaner} checked={ids.includes(p.id)} onChange={() => setIds(current => current.includes(p.id) ? current.filter(id => id !== p.id) : [...current, p.id])} />{p.name}</label>)}{ids.filter(id => !properties.some(p => p.id === id)).map(id => <p key={id} className="text-xs text-stone-500">현재 조회 범위 밖의 기존 배정이 있습니다. 변경은 관리자에게 요청해 주세요.</p>)}</div>}
          <p className="text-xs leading-6 text-stone-500">{mode === 'all' ? `이 직원을 등록한 운영자 소유의 숙소에 적용됩니다. 현재 ${properties.filter(p => p.ownerId === staff.ownerId).length}곳이 목록에 표시됩니다.` : mode === 'none' ? '새 업무를 위한 숙소 접근과 청소 오픈 알림을 해제합니다. 이미 배정된 청소 이력과 일정은 보존합니다.' : '선택한 숙소에만 업무 권한이 적용됩니다.'}</p>
          <button disabled={isSelf && !cleaner} className={`${button} bg-[var(--brand)] text-white`}>담당 숙소 저장</button></>}
      </form>}
      {tab === 'login' && <div className="space-y-5"><p className="text-sm">로그인 상태: {statuses[staff.status] || staff.status}</p>{staff.loginIdentifier && <p className="text-sm break-all">로그인 ID: {staff.loginIdentifier}</p>}
        {cleaner && <button type="button" onClick={resetLogin} className={button}>{staff.userId ? '초기 비밀번호 재발급' : '앱 로그인 만들기'}</button>}
        {cleaner && !staff.userId && <form className="space-y-3 border-t pt-4" onSubmit={event => { event.preventDefault(); void action(async () => { const result = await api(`/api/cleaners/${staff.cleanerId}/invite`, 'POST', { email: inviteEmail }); setInviteToken(result.token); }); }}><label className="block text-sm">이메일 초대로 연결하기<input required type="email" value={inviteEmail} onChange={event => setInviteEmail(event.target.value)} className={field} /></label><button className={button}>초대 링크 만들기</button>{inviteToken && <button type="button" className={button} onClick={async () => { try { await navigator.clipboard.writeText(`${location.origin}/invite/${inviteToken}`); setMessage('초대 링크를 복사했습니다.'); } catch { setError('복사하지 못했습니다.'); } }}>초대 링크 복사</button>}</form>}
        {staff.userId && !isSelf && <button type="button" className={button} onClick={async () => { if (staff.status === 'active' && !await confirmDialog('이 직원의 로그인을 중지하시겠습니까? 청소 일정과 이력은 보존됩니다.')) return; void action(() => cleaner ? cleanerUpdate({ loginEnabled: staff.status !== 'active' }) : api('/api/users', 'PUT', { id: staff.userId, status: staff.status === 'active' ? 'suspended' : 'active' })); }}>{staff.status === 'active' ? '로그인 중지' : staff.status === 'pending_invite' ? '가입 승인' : '로그인 허용'}</button>}
        {isSelf && <Link href="/admin/settings/profile" className="block text-sm underline">내 비밀번호 변경</Link>}
        {password && <div className="space-y-3 border border-emerald-200 p-4"><p className="text-sm">새 초기 비밀번호입니다. 이 화면을 닫으면 다시 표시하지 않습니다.</p><input aria-label="새 초기 비밀번호" readOnly type={visible ? 'text' : 'password'} value={password} className={field} /><label className="flex gap-2 text-sm"><input type="checkbox" checked={visible} onChange={event => setVisible(event.target.checked)} />비밀번호 표시</label><button type="button" className={button} onClick={async () => { try { await navigator.clipboard.writeText(`로그인 ID: ${staff.loginIdentifier || staff.phone}\n초기 비밀번호: ${password}`); setMessage('복사했습니다.'); } catch { setError('복사하지 못했습니다.'); } }}>로그인 정보 복사</button></div>}
        {cleaner && <div className="border-t pt-5 space-y-3"><h3 className="text-sm font-medium">개인 일정 링크</h3><p className="text-xs text-stone-500">계정 없이 배정된 일정을 확인하는 링크입니다. 로그인 중지와 별도로 유지됩니다.</p>{staff.publicToken && <button type="button" className={button} onClick={async () => { try { await navigator.clipboard.writeText(`${location.origin}/c/${staff.publicToken}`); setMessage('일정 링크를 복사했습니다.'); } catch { setError('복사하지 못했습니다.'); } }}>일정 링크 복사</button>}<button type="button" className={button} onClick={async () => { if (!await confirmDialog('기존 일정 링크를 무효화하고 새 링크를 발급하시겠습니까?')) return; void action(() => cleanerUpdate({ regenerateToken: true })); }}>일정 링크 재발급</button></div>}
      </div>}
      {tab === 'notifications' && <div className="space-y-5">{cleaner ? <><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={staff.notifyNewOpen} disabled={!staff.phone} onChange={event => void action(() => cleanerUpdate({ notifyNewOpen: event.target.checked }))} />새 청소 오픈 알림 받기</label><p className="text-xs text-stone-500">담당 숙소 배정과 휴대폰 번호를 기준으로 발송합니다.</p></> : <><p className="text-sm">고객 문의 알림 수신자는 숙소별로 지정합니다. 이 직원의 회원 정보에 등록된 이름과 휴대폰 번호를 사용합니다.</p><div className="flex flex-wrap gap-3">{properties.filter(p => staff.role === 'admin' || staff.propertyIds.includes(p.id)).map(p => <Link key={p.id} href={`/admin/properties/${p.id}/settings`} className={`${button} inline-flex items-center`}>{p.name} 알림 설정</Link>)}</div></>}</div>}
    </fieldset>
    {busy && <p role="status" className="mt-5 text-sm">저장 중…</p>}{error && <p role="alert" className="mt-5 text-sm text-red-600">{error}</p>}{message && <p role="status" className="mt-5 text-sm text-emerald-700">{message}</p>}
  </section>;
}
