[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/ical/anonjae"
  to = "https://api.beds24.com/ical/bookings.ics?roomid=665802"
  status = 301

[[redirects]]
  from = "/ical/hwayeonjae"
  to = "https://api.beds24.com/ical/bookings.ics?roomid=667806"
  status = 301

[[redirects]]
  from = "/ical/unwadang"
  to = "https://api.beds24.com/ical/bookings.ics?roomid=664844"
  status = 301
