'use client';
import { useEffect,useState } from 'react';
import { useRefetchOnReturn } from '@/lib/hooks/useRefetchOnReturn';
import { LAUNDRY_LABELS,type LaundryItem } from '@/lib/laundry';

type Batch={id:string;propertyId:string;property:{name:string};pickupDate:string;deliveryDate:string;vendor:string;vendorPhone:string;status:string;notes:string;items:LaundryItem[];version:number;history:{at:string;actor:string;action:string;note?:string}[]};
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
const fresh=():LaundryItem[]=>['수건','시트','이불 커버','베개 커버'].map(name=>({name,sent:0,received:0,damaged:0,rewash:0}));
const control='min-h-11 rounded-xl border border-stone-300 bg-white px-3 py-2 w-full';
const button='min-h-11 rounded-xl border border-stone-300 px-4 py-2 disabled:opacity-40';
function Counter({value,onChange,label}:{value:number;onChange:(value:number)=>void;label:string}) {return <div className="flex items-center gap-1"><button type="button" className={button} aria-label={label+' 줄이기'} onClick={()=>onChange(Math.max(0,value-1))}>−</button><input aria-label={label} type="number" min="0" max="10000" inputMode="numeric" className="w-16 min-h-11 text-center border rounded-lg" value={value} onChange={e=>onChange(Math.max(0,Math.min(10000,Number(e.target.value)||0)))}/><button type="button" className={button} aria-label={label+' 늘리기'} onClick={()=>onChange(Math.min(10000,value+1))}>+</button></div>;}
export default function LaundryWorkspace({embedded=false}:{embedded?:boolean}){
 const [rows,setRows]=useState<Batch[]>([]),[properties,setProperties]=useState<{id:string;name:string}[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState(''),[tab,setTab]=useState(embedded?'due':'pending');
 const [editing,setEditing]=useState<Batch|null>(null);
 const [form,setForm]=useState(false),[requestId,setRequestId]=useState(''),[propertyId,setPropertyId]=useState(''),[pickupDate,setPickup]=useState(today),[deliveryDate,setDelivery]=useState(today),[vendor,setVendor]=useState(''),[vendorPhone,setPhone]=useState(''),[notes,setNotes]=useState(''),[items,setItems]=useState(fresh);
 const [selected,setSelected]=useState<Batch|null>(null),[mode,setMode]=useState<'receive'|'correct'>('receive'),[quantities,setQuantities]=useState<LaundryItem[]>([]),[note,setNote]=useState('');
 async function load(){setError('');try{const res=await fetch('/api/laundry',{cache:'no-store'});const data=await res.json();if(!res.ok)throw Error(data.error||'불러오지 못했습니다.');setRows(data.batches);setProperties(data.properties);setPropertyId(id=>id||data.properties[0]?.id||'');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useRefetchOnReturn(load,{enabled:!form&&!selected&&!busy});
 async function mutate(payload:unknown,method='PATCH'){setBusy(true);setError('');try{const res=await fetch('/api/laundry',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw Error(data.error||'저장하지 못했습니다.');setSelected(null);setForm(false);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function openReceive(row:Batch,correct=false){setSelected(row);setMode(correct?'correct':'receive');setNote('');setQuantities(row.items.map(i=>correct?{...i}:{...i,received:0,damaged:0,rewash:0}));}
 function edit(index:number,key:keyof Omit<LaundryItem,'name'>,value:number){setQuantities(list=>list.map((i,n)=>n===index?{...i,[key]:value}:i));}
 const visible=rows.filter(r=>(!filter||r.propertyId===filter)&&(tab==='all'||tab==='due'&&!['completed','cancelled'].includes(r.status)&&(r.status==='scheduled'?r.pickupDate<=today():r.deliveryDate<=today())||tab==='today'&&(r.pickupDate===today()||r.deliveryDate===today())||tab==='pending'&&!['completed','cancelled'].includes(r.status)||tab==='attention'&&(r.items.some(i=>i.damaged+i.rewash>0)||r.deliveryDate<today()&&!['completed','cancelled'].includes(r.status))));
 return <div className="space-y-5"><header className="flex justify-between gap-3 items-center"><div><h2 className="text-xl font-semibold">{embedded?'오늘 세탁 · 수거와 입고':'세탁 관리'}</h2><p className="text-sm text-stone-500 mt-1">{embedded?'오늘 처리할 일정과 기한이 지난 세탁물을 함께 확인하세요.':'지점별 수거부터 입고 확인까지'}</p></div><button className={button+' bg-stone-900 text-white'} onClick={()=>{setEditing(null);setForm(true);setRequestId(crypto.randomUUID());setItems(fresh());setPickup(today());setDelivery(today());setNotes('');}}>수거 등록</button></header>
 <div className="flex gap-2 flex-wrap">{[...(embedded?[['due','오늘 할 일']]:[]),['pending','진행 중'],['today','오늘 일정'],['attention','확인 필요'],['all','전체']].map(([key,label])=><button key={key} className={button+(tab===key?' bg-stone-200':'')} onClick={()=>setTab(key)}>{label}</button>)}</div>
 <label className="block text-sm">숙소<select className={control} value={filter} onChange={e=>setFilter(e.target.value)}><option value="">전체 담당 숙소</option>{properties.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>
 {error&&<div role="alert" className="rounded-xl bg-red-50 text-red-800 p-4">{error}<button className={button+' ml-2'} onClick={()=>void load()}>새로고침</button></div>}
 {loading?<p role="status">세탁 정보를 불러오는 중…</p>:!visible.length?<p className="p-8 text-center text-stone-500">{tab==='due'?'오늘 처리할 세탁 일정이 없습니다. 수거 등록으로 새 일정을 추가할 수 있습니다.':'표시할 세탁 건이 없습니다.'}</p>:visible.map(row=><article className="bg-white rounded-2xl border p-4 space-y-3" key={row.id}><div className="flex justify-between gap-2"><strong>{row.property.name}</strong><span>{LAUNDRY_LABELS[row.status]}</span></div><p className="text-sm">수거 {row.pickupDate} → 배송 예정 {row.deliveryDate}</p><p className="text-sm text-stone-600">{row.vendor} {row.vendorPhone}</p>{row.notes&&<p className="text-sm whitespace-pre-wrap">{row.notes}</p>}
 <table className="w-full text-sm text-right"><thead><tr><th className="text-left">품목</th><th>보냄</th><th>입고</th><th>미입고</th></tr></thead><tbody>{row.items.map(i=><tr key={i.name} className="border-t"><td className="text-left py-2">{i.name}{i.damaged+i.rewash>0&&<span className="block text-xs text-red-700">파손 {i.damaged} · 재세탁 {i.rewash}</span>}</td><td>{i.sent}</td><td>{i.received}</td><td className={i.sent>i.received?'text-amber-700 font-semibold':''}>{i.sent-i.received}</td></tr>)}</tbody></table>
 {row.deliveryDate<today()&&!['completed','cancelled'].includes(row.status)&&<p className="text-red-700 text-sm">배송 예정일이 지났습니다.</p>}
 <div className="flex gap-2 flex-wrap">{!['completed','cancelled'].includes(row.status)&&<button className={button} disabled={busy} onClick={()=>{setEditing(row);setForm(true);setPropertyId(row.propertyId);setPickup(row.pickupDate);setDelivery(row.deliveryDate);setVendor(row.vendor);setPhone(row.vendorPhone);setNotes(row.notes);setItems(row.items);}}>일정·배송 수정</button>}{row.status==='scheduled'?<><button disabled={busy} className={button} onClick={()=>void mutate({id:row.id,version:row.version,action:'collect'})}>수거 완료</button><button disabled={busy} className={button} onClick={()=>{const reason=window.prompt('취소 사유');if(reason?.trim())void mutate({id:row.id,version:row.version,action:'cancel',note:reason});}}>일정 취소</button></>:!['completed','cancelled'].includes(row.status)&&<><button disabled={busy} className={button+' bg-stone-900 text-white'} onClick={()=>openReceive(row)}>입고 확인</button>{['washing','shipping'].map(action=><button disabled={busy||row.status===action} key={action} className={button} onClick={()=>void mutate({id:row.id,version:row.version,action})}>{LAUNDRY_LABELS[action]}</button>)}</>}{row.status!=='cancelled'&&<button className={button} onClick={()=>openReceive(row,true)}>수량 정정</button>}</div>
 <details className="text-xs text-stone-500"><summary className="cursor-pointer py-2">작업 이력</summary>{row.history.map((h,i)=><p key={i} className="py-1">{new Date(h.at).toLocaleString('ko-KR')} · {h.actor} · {({collect:'수거 완료',washing:'세탁 중',shipping:'배송 중',receive:'입고 확인',correct:'수량 정정',cancel:'취소',schedule:'일정·배송 수정'} as Record<string,string>)[h.action]||h.action} {h.note}</p>)}</details></article>)}
 <p className="text-xs text-stone-500">최근 수거 건 최대 300개를 표시합니다. 파손·재세탁 수량은 입고 수량에 포함되며 별도로 표시됩니다.</p>
 {form&&<div className="fixed inset-0 z-[60] bg-black/40 overflow-y-auto p-3"><form role="dialog" aria-modal="true" aria-label="수거 등록" className="bg-white rounded-2xl max-w-xl mx-auto p-5 space-y-4" onSubmit={e=>{e.preventDefault();if(editing)void mutate({id:editing.id,version:editing.version,action:'schedule',schedule:{pickupDate,deliveryDate,vendor,vendorPhone,notes}});else void mutate({id:requestId,propertyId,pickupDate,deliveryDate,vendor,vendorPhone,notes,items:items.filter(i=>i.sent>0)},'POST');}}><h2 className="text-xl">세탁물 수거 등록</h2>
 {error&&<p role="alert" className="text-red-700">{error}</p>}
 <label className="block">숙소<select disabled={!!editing} required className={control} value={propertyId} onChange={e=>setPropertyId(e.target.value)}>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label>수거 예정일<input required type="date" className={control} value={pickupDate} onChange={e=>setPickup(e.target.value)}/></label><label>배송 예정일<input required type="date" min={pickupDate} className={control} value={deliveryDate} onChange={e=>setDelivery(e.target.value)}/></label></div>
 <label className="block">세탁업체<input required maxLength={100} className={control} value={vendor} onChange={e=>setVendor(e.target.value)}/></label><label className="block">업체·기사 연락처<input type="tel" maxLength={40} className={control} value={vendorPhone} onChange={e=>setPhone(e.target.value)}/></label>
 {!editing&&items.map((item,index)=><div key={index} className="flex justify-between items-center gap-2"><input aria-label={'품목 '+(index+1)} className={control+' max-w-40'} value={item.name} maxLength={60} onChange={e=>setItems(list=>list.map((v,n)=>n===index?{...v,name:e.target.value}:v))}/><Counter label={item.name+' 보낼 수량'} value={item.sent} onChange={value=>setItems(list=>list.map((v,n)=>n===index?{...v,sent:value}:v))}/></div>)}<button type="button" className={button} disabled={!!editing||items.length>=30} onClick={()=>setItems(list=>[...list,{name:'',sent:0,received:0,damaged:0,rewash:0}])}>품목 추가</button>
 <label className="block">전달 장소·메모<textarea maxLength={2000} className={control} value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="flex gap-2"><button disabled={busy} className={button+' bg-stone-900 text-white'}>{busy?'저장 중…':(editing?'일정 저장':'수거 예정 저장')}</button><button type="button" disabled={busy} className={button} onClick={()=>setForm(false)}>닫기</button></div></form></div>}
 {selected&&<div className="fixed inset-0 z-[60] bg-black/40 overflow-y-auto p-3"><form role="dialog" aria-modal="true" aria-label="입고 및 정정" className="bg-white rounded-2xl max-w-xl mx-auto p-5 space-y-4" onSubmit={e=>{e.preventDefault();void mutate({id:selected.id,version:selected.version,action:mode,note,...(mode==='correct'?{items:quantities}:{incoming:quantities.map(i=>({name:i.name,quantity:i.received,damaged:i.damaged,rewash:i.rewash}))})});}}><h2 className="text-xl">{selected.property.name} · {mode==='receive'?'입고 확인':'수량 정정'}</h2>{error&&<p role="alert" className="text-red-700">{error}</p>}
 {mode==='receive'&&<button type="button" className={button} onClick={()=>setQuantities(list=>list.map((i,n)=>({...i,received:selected.items[n].sent-selected.items[n].received,damaged:0,rewash:0})))}>남은 수량 전량 입고</button>}
 {quantities.map((item,index)=><fieldset key={item.name} className="border rounded-xl p-3 space-y-3"><legend>{item.name} · 미입고 {selected.items[index].sent-selected.items[index].received}</legend>{(mode==='correct'?['sent','received','damaged','rewash'] as const:['received','damaged','rewash'] as const).map(key=><div key={key} className="flex items-center justify-between gap-2"><span>{key==='sent'?'보낸 총수량':key==='received'?(mode==='correct'?'누적 입고':'이번 입고'):key==='damaged'?'그중 파손':'그중 재세탁'}</span><Counter label={item.name+' '+key} value={item[key]} onChange={value=>edit(index,key,value)}/></div>)}</fieldset>)}
 <label className="block">{mode==='correct'?'정정 사유 (필수)':'배송·오염·파손 메모'}<textarea required={mode==='correct'} maxLength={2000} className={control} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="flex gap-2"><button disabled={busy} className={button+' bg-stone-900 text-white'}>{busy?'저장 중…':'확인 후 저장'}</button><button type="button" disabled={busy} className={button} onClick={()=>setSelected(null)}>닫기</button></div></form></div>}
 </div>;
}
