export const baseCopy={
  en:{tag:'A LITTLE PREPARATION. A LOVELY STAY.',title:'Your Seoul stay,\nbeautifully prepared.',intro:'The essentials for your arrival, a comfortable ride from the airport, and a little inspiration for your days in Seoul.',stay:'Your stay',pickup:'Airport pickup',tours:'Local experiences',guide:'YOUR ARRIVAL GUIDE',essentials:'Settle in with ease.',checkin:'Check-in',checkout:'Check-out',luggage:'Luggage storage',luggageText:'You’ll find the luggage storage area to the right of the accommodation. Please ask your host about available hours and any fees.',address:'Find your way',map:'Open map',parking:'Coming by car?',parkingText:'Use a nearby paid car park: Blue Giraffe private parking (58-1 Hwa-dong), Jeongdok Library, the National Museum of Modern and Contemporary Art, or Hyundai Building. Hyundai Building is our suggested lower-cost option; check current rates and availability. You can also use the Modu Parking app.',ride:'FROM ARRIVAL TO YOUR DOOR',rideTitle:'An easier start\nto your trip.',rideText:'Arrange a van taxi from Incheon Airport to Byulha before you travel. Tell us your flight details and we’ll check availability for you.',price:'KRW 100,000',priceNote:'Incheon Airport van taxi · advance reservation required',checkNote:'Vehicle capacity, luggage space, any additional charges and the final fare will be confirmed by your host. Submitting this form does not confirm a booking or charge a payment.',request:'Request airport pickup',steps:['Send your flight details','Your host checks availability','Receive your booking confirmation'],formTitle:'Tell us about your arrival.',formSubtitle:'Arrival date and time should be in Korea local time (KST). This service is for travel from Incheon Airport to the accommodation.',name:'Reservation name',email:'Email',phone:'Phone (include country code)',date:'Arrival date',time:'Arrival time (KST)',flight:'Flight number',passengers:'Passengers',bags:'Pieces of luggage',message:'Anything else we should know? (optional)',consent:'I agree that void anchae may use these details to review and contact me about this pickup request. Please do not enter passport or payment information.',submit:'Send pickup request',sending:'Sending…',received:'Your request is in.',receivedText:'Your host will review the details and contact you using the email or phone number you provided. Please wait for a separate confirmation before making travel arrangements.',reference:'Request reference',retryText:'We couldn’t complete the request. Your details are still here; please try again or contact your host through your booking channel.',discover:'MAKE ROOM FOR A LITTLE DISCOVERY',discoverTitle:'More than a place to stay.',discoverText:'Explore the experiences currently offered by our team. Each experience page has its own schedule, prices and booking details.',tourButton:'View experience',allTours:'Explore all experiences',tourError:'Experiences could not be loaded.',retry:'Try again',noTours:'New experiences are being prepared. Ask your host for local recommendations.',from:'From',priceOnPage:'See prices on the experience page',help:'A question before you arrive?',helpText:'Send us a message through the channel where you booked your stay. For pickup requests, we’ll use the contact details you submit above.',footer:'A considered stay, a little closer to Seoul.',saved:'Submitting a request does not confirm a booking.'},
  ko:{tag:'여행의 시작을 조금 더 편안하게',title:'서울에서의 머무름,\n도착 전부터 편안하게.',intro:'체크인에 필요한 안내부터 공항에서 오는 길, 서울에서 즐길 경험까지. 별하재에서의 여행을 미리 준비해 보세요.',stay:'숙소 안내',pickup:'공항 픽업',tours:'투어·체험',guide:'도착 전에 알아두세요',essentials:'편안한 머무름의 시작.',checkin:'체크인',checkout:'체크아웃',luggage:'짐 보관',luggageText:'짐 보관소는 숙소 오른편에 마련되어 있습니다. 이용 가능 시간과 비용은 담당자에게 확인해 주세요.',address:'오시는 길',map:'지도에서 보기',parking:'차량으로 오시나요?',parkingText:'푸른기린 민영주차장(화동 58-1), 정독도서관, 현대미술관 또는 현대빌딩 주차장을 이용해 주세요. 현대빌딩은 비교적 저렴한 선택지로 안내드리며, 실제 요금과 빈자리는 이용 전 확인해 주세요. ‘모두의주차장’에서 주차장을 찾으셔도 좋습니다.',ride:'공항에서 숙소까지',rideTitle:'여행의 첫 이동을\n가볍게.',rideText:'인천공항에서 별하재로 오시는 밴택시를 미리 요청하세요. 항공편과 인원, 짐 수량을 알려주시면 담당자가 예약 가능 여부를 확인합니다.',price:'100,000원',priceNote:'인천공항 밴택시 기준 · 사전 예약 필수',checkNote:'차량 정원, 수하물 수용량, 추가요금과 최종 금액은 담당자 확인 후 안내합니다. 신청만으로 예약이 확정되거나 결제되지 않습니다.',request:'공항 픽업 요청하기',steps:['항공편 정보로 요청 접수','담당자가 차량·일정 확인','별도 안내 후 예약 확정'],formTitle:'도착 일정을 알려주세요.',formSubtitle:'인천공항에서 숙소로 오는 편도 요청입니다. 도착 날짜와 시간은 한국 현지 시간(KST)으로 입력해 주세요.',name:'숙소 예약자 이름',email:'이메일',phone:'연락처 (해외 번호는 국가번호 포함)',date:'공항 도착일',time:'도착 시간 (한국 기준)',flight:'항공편명',passengers:'탑승 인원',bags:'수하물 개수',message:'추가 요청사항 (선택)',consent:'픽업 요청 확인 및 연락을 위해 void anchae가 입력한 정보를 이용하는 데 동의합니다. 여권번호나 결제 정보는 입력하지 마세요.',submit:'픽업 요청 접수',sending:'접수 중…',received:'픽업 요청을 접수했습니다.',receivedText:'담당자가 내용을 확인하고 입력하신 이메일 또는 연락처로 안내드립니다. 별도의 확정 안내를 받은 후 이동 계획을 확정해 주세요.',reference:'접수 번호',retryText:'요청을 완료하지 못했습니다. 입력 내용은 유지됩니다. 다시 시도하거나 숙소 예약 채널로 문의해 주세요.',discover:'서울을 조금 더 가까이',discoverTitle:'머무름에 경험을 더하세요.',discoverText:'운영 중인 투어와 체험을 살펴보세요. 각 상품의 상세 페이지에서 일정과 요금, 예약 안내를 확인할 수 있습니다.',tourButton:'체험 자세히 보기',allTours:'전체 투어·체험 보기',tourError:'투어 정보를 불러오지 못했습니다.',retry:'다시 불러오기',noTours:'새로운 경험을 준비하고 있습니다. 주변 추천 장소는 담당자에게 문의해 주세요.',from:'부터',priceOnPage:'상세 페이지에서 요금 확인',help:'도착 전 궁금한 점이 있나요?',helpText:'숙소를 예약하신 채널의 메시지로 문의해 주세요. 픽업 요청은 위에 남겨주신 이메일 또는 연락처로 안내드립니다.',footer:'서울의 일상에 조금 더 가까운 머무름.',saved:'요청 접수 후 담당자의 별도 예약 확정이 필요합니다.'}
};

const en = {
  ...baseCopy.en,
  intro: 'The essentials for your arrival at {name}, a comfortable ride from the airport, and inspiration for your days in Seoul.',
  rideText: 'Request a van taxi from Incheon Airport to {name} before you travel. Tell us your flight details, passenger count and luggage so we can check availability.',
  luggageOther: 'Please ask your host through your booking channel about luggage storage availability, location and hours.',
  parking: 'Parking information',
  parkingText: 'Please use one of the nearby car parks below or the Modu Parking app (모두의주차장).',
  parkingPlaces: ['Blue Giraffe private car park (푸른기린 민영주차장): 58-1 Hwa-dong', 'Jeongdok Library car park (정독도서관)', 'National Museum of Modern and Contemporary Art car park (현대미술관)', 'Hyundai Building car park (현대빌딩)'],
  parkingPrice: 'Hyundai Building is the least expensive option among the car parks we recommend. Actual charges may vary depending on the length of your stay and the car park’s policies.',
  parkingCheck: 'Check fees, opening hours, available spaces and reservation availability directly with the car park or through Modu Parking.',
  home: 'Your home in Seoul', region: 'Bukchon, Seoul', sectionLabel: 'Page sections', language: 'Language', guideLabel: 'Guest guide',
  loading: 'Loading experiences', minute: 'min', startingPrice: 'From KRW {price}', slowSeoul: 'Seoul, slowly.',
  inputError: 'Please check your arrival date, time, flight number, contact details and consent.',
  rateError: 'Too many requests. Please wait a few minutes and try again.',
  tourLanguage: 'Experience detail pages may be available in their original language only.',
};
type GuideCopy = typeof en;
const ko: GuideCopy = {
  ...baseCopy.ko,
  intro: '체크인에 필요한 안내부터 공항에서 오는 길, 서울에서 즐길 경험까지. {name}에서의 여행을 미리 준비해 보세요.',
  rideText: '인천공항에서 {name}까지 오시는 밴택시를 미리 요청하세요. 항공편과 인원, 짐 수량을 알려주시면 담당자가 예약 가능 여부를 확인합니다.',
  luggageOther: '짐 보관 가능 여부와 위치, 이용 시간은 숙소 예약 채널로 담당자에게 문의해 주세요.',
  parking: '주차 안내',
  parkingText: '주차는 아래 주변 주차장 또는 ‘모두의주차장’을 이용해 주세요.',
  parkingPlaces: ['푸른기린 민영주차장: 화동 58-1번지', '정독도서관 주차장', '현대미술관 주차장', '현대빌딩 주차장'],
  parkingPrice: '숙소에서 안내하는 주차장 중 현대빌딩 주차장이 가장 저렴한 선택지입니다. 다만 실제 요금은 이용 시간과 주차장 정책에 따라 달라질 수 있습니다.',
  parkingCheck: '주차 요금, 운영시간, 빈자리 및 예약 가능 여부는 해당 주차장이나 ‘모두의주차장’에서 확인해 주세요.',
  home: '서울에서 머무는 나의 공간', region: '서울 북촌', sectionLabel: '페이지 안내', language: '언어', guideLabel: '게스트 안내',
  loading: '투어 불러오는 중', minute: '분', startingPrice: '{price}원부터', slowSeoul: '서울을 천천히.',
  inputError: '도착 날짜·시간, 항공편명, 연락처와 개인정보 동의를 확인해 주세요.',
  rateError: '요청이 많습니다. 잠시 후 다시 시도해 주세요.',
  tourLanguage: '투어 상세 페이지는 등록된 원문 언어로 제공될 수 있습니다.',
};
const zh: GuideCopy = {
  tag: '让旅途从抵达前就轻松开始', title: '首尔之旅，\n从容准备，安心入住。',
  intro: '从入住须知、机场交通到首尔体验，为您提前准备好在 {name} 的旅程。',
  stay: '住宿指南', pickup: '机场接机', tours: '当地体验', guide: '抵达前须知', essentials: '轻松开启入住时光。',
  checkin: '入住时间', checkout: '退房时间', luggage: '行李寄存',
  luggageText: '行李寄存处位于住宿右侧。开放时间及费用请向工作人员确认。',
  luggageOther: '如需寄存行李，请通过预订渠道向工作人员确认是否可用、具体位置和使用时间。',
  address: '如何抵达', map: '查看地图', parking: '停车指南',
  parkingText: '请使用以下周边停车场，或通过“모두의주차장”（Modu Parking）查找停车位。',
  parkingPlaces: ['蓝色长颈鹿私人停车场（푸른기린 민영주차장）：花洞 58-1', '正读图书馆停车场（정독도서관）', '国立现代美术馆停车场（현대미술관）', '现代大厦停车场（현대빌딩）'],
  parkingPrice: '在我们介绍的停车场中，现代大厦停车场是最便宜的选择。但实际费用可能因停车时长及停车场政策而异。',
  parkingCheck: '停车费、营业时间、空位及是否可预约，请直接向停车场或通过 Modu Parking 确认。',
  ride: '从机场到住宿', rideTitle: '让旅途的第一程\n更加轻松。',
  rideText: '请提前申请从仁川机场前往 {name} 的商务车出租车。提供航班、乘客人数和行李数量后，工作人员将确认是否可安排。',
  price: '100,000 韩元', priceNote: '仁川机场商务车出租车参考价 · 需提前预约',
  checkNote: '车辆载客量、行李空间、附加费用及最终价格将由工作人员确认。提交申请不代表预订已确认，也不会产生扣款。',
  request: '申请机场接机', steps: ['提交航班信息', '工作人员确认车辆和时间', '收到单独的预订确认'],
  formTitle: '请告诉我们您的抵达安排。', formSubtitle: '此服务为仁川机场至住宿的单程接机。请按韩国当地时间（KST）填写抵达日期和时间。',
  name: '住宿预订人姓名', email: '电子邮箱', phone: '联系电话（含国家区号）', date: '抵达机场日期', time: '抵达时间（韩国时间）', flight: '航班号', passengers: '乘客人数', bags: '行李件数', message: '其他需求（选填）',
  consent: '我同意 void anchae 使用所填信息审核本次接机申请并与我联系。请勿填写护照号码或支付信息。',
  submit: '提交接机申请', sending: '正在提交…', received: '您的接机申请已收到。',
  receivedText: '工作人员审核后将通过您提供的电子邮箱或电话联系您。请收到单独的确认通知后再确定出行安排。', reference: '申请编号',
  retryText: '申请未能完成。您填写的内容仍保留，请重试，或通过住宿预订渠道联系工作人员。',
  discover: '更近地感受首尔', discoverTitle: '为住宿增添一份体验。',
  discoverText: '浏览目前提供的游览和体验项目。请在各项目详情页查看日期、价格和预订信息。',
  tourButton: '查看体验详情', allTours: '查看全部体验', tourError: '无法加载体验信息。', retry: '重试', noTours: '新的体验正在准备中。欢迎向工作人员咨询周边推荐。', from: '起', priceOnPage: '请在详情页查看价格',
  help: '抵达前还有疑问？', helpText: '请通过预订住宿时使用的渠道联系我们。接机申请将通过您在上方提供的邮箱或电话回复。', footer: '走近首尔日常的住宿时光。', saved: '提交申请后，仍需工作人员单独确认预订。',
  home: '您在首尔的家', region: '首尔北村', sectionLabel: '页面导航', language: '语言', guideLabel: '入住指南', loading: '正在加载体验', minute: '分钟', startingPrice: '{price} 韩元起', slowSeoul: '慢慢感受首尔。',
  inputError: '请检查抵达日期、时间、航班号、联系方式及个人信息使用同意选项。', rateError: '请求过于频繁，请稍后再试。', tourLanguage: '体验详情页可能仅提供原始语言版本。',
};
const ja: GuideCopy = {
  tag: '旅の始まりを、もう少し快適に', title: 'ソウルでの滞在を、\n到着前から心地よく。',
  intro: 'チェックインのご案内から空港からの移動、ソウルでの体験まで。{name}での旅を事前にご準備ください。',
  stay: '宿泊のご案内', pickup: '空港送迎', tours: 'ツアー・体験', guide: 'ご到着前のご案内', essentials: '心地よい滞在の始まり。',
  checkin: 'チェックイン', checkout: 'チェックアウト', luggage: 'お荷物のお預かり',
  luggageText: '荷物預かり場所は宿泊施設の右側にあります。利用可能時間と料金は担当者にご確認ください。',
  luggageOther: '荷物のお預かりの可否、場所、利用時間は、ご予約時の連絡手段で担当者にお問い合わせください。',
  address: 'アクセス', map: '地図を見る', parking: '駐車場のご案内',
  parkingText: '以下の周辺駐車場、または「모두의주차장」（Modu Parking）をご利用ください。',
  parkingPlaces: ['青いキリン民営駐車場（푸른기린 민영주차장）：花洞58-1番地', '正読図書館駐車場（정독도서관）', '国立現代美術館駐車場（현대미술관）', '現代ビル駐車場（현대빌딩）'],
  parkingPrice: 'ご案内している駐車場の中では、現代ビル駐車場が最も安い選択肢です。ただし、実際の料金は利用時間や駐車場の規定によって異なる場合があります。',
  parkingCheck: '料金、営業時間、空き状況、予約の可否は、各駐車場または Modu Parking でご確認ください。',
  ride: '空港から宿泊施設まで', rideTitle: '旅の最初の移動を、\n身軽に。',
  rideText: '仁川空港から{name}までのバンタクシーを事前にお申し込みください。便名、人数、お荷物の数をお知らせいただき、担当者が手配の可否を確認します。',
  price: '100,000ウォン', priceNote: '仁川空港バンタクシーの目安料金 · 事前予約必須',
  checkNote: '乗車定員、荷物の積載量、追加料金および最終料金は担当者が確認してご案内します。お申し込みだけでは予約は確定せず、お支払いも発生しません。',
  request: '空港送迎を申し込む', steps: ['フライト情報を送信', '担当者が車両・日程を確認', '別途ご案内のうえ予約確定'],
  formTitle: 'ご到着予定をお知らせください。', formSubtitle: '仁川空港から宿泊施設への片道送迎です。到着日時は韓国現地時間（KST）でご入力ください。',
  name: '宿泊予約者名', email: 'メールアドレス', phone: '電話番号（国番号を含む）', date: '空港到着日', time: '到着時刻（韓国時間）', flight: '便名', passengers: '乗車人数', bags: 'お荷物の個数', message: 'その他のご要望（任意）',
  consent: '送迎のお申し込みの確認および連絡のため、void anchae が入力情報を利用することに同意します。パスポート番号や決済情報は入力しないでください。',
  submit: '送迎を申し込む', sending: '送信中…', received: '送迎のお申し込みを受け付けました。',
  receivedText: '内容を確認後、ご入力のメールアドレスまたは電話番号に担当者からご連絡します。別途予約確定のご案内を受け取ってから、移動予定を確定してください。', reference: '受付番号',
  retryText: 'お申し込みを完了できませんでした。入力内容は保持されています。再度お試しいただくか、ご予約時の連絡手段でお問い合わせください。',
  discover: 'ソウルをもっと身近に', discoverTitle: '滞在に、体験を添えて。',
  discoverText: '現在ご案内しているツアーや体験をご覧ください。日程・料金・予約方法は各商品の詳細ページでご確認いただけます。',
  tourButton: '体験の詳細を見る', allTours: 'すべての体験を見る', tourError: '体験情報を読み込めませんでした。', retry: '再試行', noTours: '新しい体験を準備中です。周辺のおすすめスポットは担当者にお尋ねください。', from: 'から', priceOnPage: '料金は詳細ページをご覧ください',
  help: 'ご到着前にご質問はありますか？', helpText: '宿泊をご予約いただいた際の連絡手段でお問い合わせください。送迎のお申し込みについては、上記のメールアドレスまたは電話番号にご連絡します。', footer: 'ソウルの日常に、少し近づく滞在。', saved: 'お申し込み後、担当者による別途予約確定が必要です。',
  home: 'ソウルでのあなたの居場所', region: 'ソウル・北村', sectionLabel: 'ページ内ナビゲーション', language: '言語', guideLabel: 'ゲストガイド', loading: '体験を読み込み中', minute: '分', startingPrice: '{price}ウォンから', slowSeoul: 'ゆっくり、ソウル。',
  inputError: '到着日時、便名、連絡先、個人情報の利用への同意をご確認ください。', rateError: 'リクエストが多すぎます。しばらくしてから再度お試しください。', tourLanguage: '体験の詳細ページは、登録された原文の言語のみで提供される場合があります。',
};

export const guestGuideCopy = { en, ko, zh, ja };
