export const publicCopy: Record<string, string> = {
  '투어 둘러보기': 'Explore tours',
  '영주 가이드': 'Yeongju guide',
  '북촌 가이드': 'Bukchon guide',
  '10월 오픈 예정':'Opening in October',
  '예약 가능 여부를 확인 중입니다.':'Checking availability.', '판매 가능한 객실이 없습니다.':'No rooms are available.', '체크인이 제한된 날짜입니다.':'Check-in is not available on this date.', '1~30박 일정을 선택해주세요.':'Choose a stay of 1–30 nights.', '체크아웃 가능 여부를 확인 중입니다.':'Checking check-out availability.', '체크아웃이 제한된 날짜입니다.':'Check-out is not available on this date.', '일정 중 판매 가능한 객실이 없는 날짜가 있습니다.':'A room is unavailable on one or more selected nights.', '취소·환불 규정에 동의해주세요.':'Please agree to the cancellation and refund policy.',
  '브랜드':'Our story', '공간':'Stays', '투어':'Tours', '입점 안내':'Partner with us', '호스팅 지원 플랫폼':'Hosting platform', '주 메뉴':'Main navigation', 'void anchae 홈':'VOID ANCHAE home', '예약하기':'Book a stay', '관리자':'Admin', '메뉴 닫기':'Close menu', '메뉴 열기':'Open menu',
  '한옥에서 바라보는 초록빛 풍경과 산 능선':'Green landscape and mountains seen from a hanok', '배경 영상 일시정지':'Pause background video', '배경 영상 재생':'Play background video', '그저 머물러도':'Simply stay.', '충분합니다.':'That is enough.',
  '머무를 한옥':'Find your stay', '머물고 싶은 한옥':'Your hanok', '숙소를 선택해주세요':'Select a stay', '날짜 · 요금 확인':'Dates & rates', '숙소 예약으로 바로가기':'Skip to booking', '머무는 공간':'Our stays',
  '안온재':'Anonjae', '운와당':'Unwadang', '화연재':'Hwayeonjae', '도원재':'Dowonjae', '별하재':'Byulhajae', '자락헌':'Jarakheon', '북촌':'Bukchon, Seoul', '경북 영주':'Yeongju, Gyeongbuk', '삼청동':'Samcheong-dong, Seoul',
  '대문을 지나 안으로 들어오면':'As you step through the gate,', '말소리는 낮아지고, 걸음은 느려집니다.':'voices soften and footsteps slow.', '이곳에서는 무언가를 하지 않아도 괜찮습니다.':'There is nothing you need to do here.', '그저 머무르는 것만으로 충분합니다.':'Simply being here is enough.',
  'VOID ANCHAE는 편안함의 이유를':'At VOID ANCHAE, comfort comes', '공간의 크기나 장식보다':'less from size or decoration', '비워 둔 여백에서 찾았습니다.':'than from the room we leave for you.', '당신이 들어와야 비로소 완성되는 공간.':'A space that feels complete when you arrive.', '머무는 동안의 시간과 마음이':'A hanok that quietly holds', '자연스럽게 스며드는 한옥입니다.':'the moments and feelings of your stay.', '서두르지 않아도 좋습니다.':'There is no need to hurry.', '가장 나다운 모습으로 쉬어갈 수 있도록':'We leave a place for you', '당신의 자리를 비워 두겠습니다.':'to rest and feel like yourself.', '그저 머물러도 충분한 곳':'A place where simply staying is enough.', '당신이 들어와야':'A space made complete', '비로소 완성되는 공간.':'by your presence.', '당신이 머무는 한옥, VOID ANCHAE':'Your hanok stay, VOID ANCHAE', '공간 둘러보기':'Explore our stays',
  '예약 가능 날짜를 불러오지 못했습니다.':'Unable to load availability.', '날짜 조회에 실패했습니다.':'Unable to load dates.', '요금을 불러오지 못했습니다.':'Unable to load rates.', '요금 조회에 실패했습니다.':'Unable to retrieve rates.', '지난 날짜':'Past date', '현재 온라인 결제를 준비 중입니다. 잠시 후 다시 시도해주세요.':'Online payment is temporarily unavailable. Please try again later.', '예약 실패':'Booking failed', '예약에 실패했습니다. 다시 시도해주세요.':'Booking failed. Please try again.', '숙소를 찾을 수 없습니다.':'Stay not found.', '메인으로 돌아가기':'Back to home', '메인으로':'Home',
  '이전 이미지':'Previous image', '다음 이미지':'Next image', '체크인':'Check-in', '체크아웃':'Check-out', '최대':'Up to ', '인':' guests', '크게 보기':'Enlarge photo', '이전 사진':'Previous photo', '다음 사진':'Next photo', '좌우로 밀어 넘기기 · 사진을 누르면 크게 보기':'Swipe to browse · Tap to enlarge', '오픈 예정':'Coming soon', '은 곧 새로운 손님을 맞이할 준비를 하고 있습니다. 오픈 소식은 홈에서 먼저 안내드리겠습니다.':'will welcome guests soon. Opening updates will appear on our home page.',
  '날짜 선택':'Select dates', '체크인 날짜를 선택해주세요.':'Choose your check-in date.', '체크아웃 날짜를 선택해주세요.':'Choose your check-out date.', '날짜 다시 불러오기':'Reload dates', '예약 가능 날짜를 확인하고 있습니다…':'Checking availability…', '숙소의 최신 판매 일정입니다. 날짜·인원 선택 후 최종 요금을 확인합니다.':'Select dates and guests to see the latest rate.', '체크인 · 최소':' check-in · Minimum ', '확인 중':'Checking', '박':' nights', '날짜 선택 초기화':'Clear dates', '이전 달':'Previous month', '다음 달':'Next month', '일':'Sun', '월':'Mon', '화':'Tue', '수':'Wed', '목':'Thu', '금':'Fri', '토':'Sat', '체크아웃 가능':'Check-out available', '날짜 선택 가능':'Available', '판매 마감':'Unavailable', '선택됨':'Selected', '이 일정으로 예약 정보 입력':'Continue with these dates', '예약':'Reservation', '예약 정보를 입력해주세요.':'Enter your guest details.', '닫기':'Close', '날짜 다시 선택':'Change dates', '인원':'Guests', '인원 감소':'Fewer guests', '인원 증가':'More guests', '이름':'Full name', '홍길동':'Full name as on your passport', '연락처':'Phone (including country code)', '이메일 주소':'Email address',
  '총 숙박요금':'Total stay price', '숙박요금':'Stay price', '선택한 날짜의 요금을 확인하고 있습니다…':'Checking rates for your dates…', '박 ·':' nights · ', '명':' guests', '결제 전 요금과 예약 가능 여부를 다시 확인합니다. PayPal 결제 시 다음 화면에서 USD 금액을 확인할 수 있습니다.':'We recheck availability and rates before payment. For PayPal, the USD total is shown on the next screen.', '표시 금액은 숙박요금입니다. 세금·청소비 등 필수 추가 요금의 포함 여부와 최종 금액은 예약 시 확인해주세요.':'Check the final total and whether taxes, cleaning and other mandatory fees are included before booking.',
  '기본 숙박요금':'Base stay price', '추가':'Extra guests: ', '인 · 숙박 1회':' guests · per stay', '반려견':'Dogs: ', '마리 · 숙박 1회':' dogs · per stay', '숙박 옵션':'Stay options', '기준':'Includes ', '인 · 추가 인원 1인':' guests · Each extra guest: KRW ', '원 / 숙박 1회':' per stay', '선택한 총 인원에서 기준 인원을 초과한 인원만 자동 계산합니다. 연박에도 옵션 요금은 한 번만 부과됩니다.':'Extra guest fees apply only above the included occupancy. Option fees are charged once per stay, including multi-night stays.', '반려견 동반 · 최대':'Dogs · Maximum ', '마리':' dogs', '동반하지 않음':'No dogs', '1마리 · 70,000원 / 숙박 1회':'1 dog · KRW 70,000 per stay', '2마리 · 100,000원 / 숙박 1회':'2 dogs · KRW 100,000 per stay', '도원재는 반려견 입실이 불가합니다.':'Dogs are not permitted at Dowonjae.',
  '다음 화면에서 최종 요금과 취소 규정을 확인합니다.':'Review the total price and cancellation policy on the next screen.', '결제 페이지로 이동 중...':'Opening payment page…', '먼저 캘린더에서 체크인 날짜를 선택해주세요':'Choose a check-in date on the calendar first.', '체크아웃 날짜를 선택해주세요':'Choose your check-out date.', '← → 이동 · ESC 닫기':'← → Browse · ESC Close',
  'PayPal 결제창을 준비하지 못했습니다. 다시 시도해주세요.':'Unable to open PayPal. Please try again.', '결제 처리 중 오류가 발생했습니다.':'An error occurred while processing payment.', '테스트 결제 / TEST — 실제 결제가 아닙니다.':'TEST — No real payment will be taken.', '일정·금액·취소 규정에 동의합니다.':'I agree to the dates, total price and cancellation policy.', '처리 결과를 확인 중입니다. 새 예약이나 추가 결제를 하지 말고 이 페이지에서 확인해주세요.':'Please wait here while we check the result. Do not create another booking or payment.', 'Overseas-issued card / 해외 발급 카드':'Overseas-issued card',
};

export function translatePublic(text: string, language: 'ko' | 'en'): string {
  const key = text.trim().replace(/\s+/g, ' ');
  const bilingual = key.match(/^(.+?)\s+\/\s+([A-Za-z].*)$/);
  if (language === 'ko') return bilingual && /[가-힣]/.test(bilingual[1]) ? bilingual[1] : text;
  const stayLimit = key.match(/^선택한 일정은 (최소|최대) (\d+)박(부터|까지) 예약할 수 있습니다\.$/);
  if (stayLimit) return `This stay requires ${stayLimit[1] === '최소' ? 'at least' : 'no more than'} ${stayLimit[2]} nights.`;
  return publicCopy[key] ?? (bilingual ? bilingual[2] : text);
}
