// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(public)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/(public)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/book/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/[id]">> = Specific
  const handler = {} as typeof import("../../app/(public)/book/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/book/checkout/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/checkout/[orderId]">> = Specific
  const handler = {} as typeof import("../../app/(public)/book/checkout/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/brand/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand">> = Specific
  const handler = {} as typeof import("../../app/(public)/brand/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide">> = Specific
  const handler = {} as typeof import("../../app/(public)/guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/guide/yeongju/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide/yeongju">> = Specific
  const handler = {} as typeof import("../../app/(public)/guide/yeongju/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/tours/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tours/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(public)/tours/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(public)/tours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tours">> = Specific
  const handler = {} as typeof import("../../app/(public)/tours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/api-clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/api-clients">> = Specific
  const handler = {} as typeof import("../../app/admin/api-clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bookings">> = Specific
  const handler = {} as typeof import("../../app/admin/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/calendar">> = Specific
  const handler = {} as typeof import("../../app/admin/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cleaners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cleaners">> = Specific
  const handler = {} as typeof import("../../app/admin/cleaners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cleaning-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cleaning-report">> = Specific
  const handler = {} as typeof import("../../app/admin/cleaning-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/cleaning-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/cleaning-requests">> = Specific
  const handler = {} as typeof import("../../app/admin/cleaning-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/guest-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/guest-services">> = Specific
  const handler = {} as typeof import("../../app/admin/guest-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/guests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/guests">> = Specific
  const handler = {} as typeof import("../../app/admin/guests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations">> = Specific
  const handler = {} as typeof import("../../app/admin/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/issues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/issues">> = Specific
  const handler = {} as typeof import("../../app/admin/issues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/laundry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/laundry">> = Specific
  const handler = {} as typeof import("../../app/admin/laundry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/messages">> = Specific
  const handler = {} as typeof import("../../app/admin/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/ops/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ops">> = Specific
  const handler = {} as typeof import("../../app/admin/ops/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payments">> = Specific
  const handler = {} as typeof import("../../app/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/properties/[id]/camera/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/properties/[id]/camera">> = Specific
  const handler = {} as typeof import("../../app/admin/properties/[id]/camera/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/properties/[id]/channels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/properties/[id]/channels">> = Specific
  const handler = {} as typeof import("../../app/admin/properties/[id]/channels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/properties/[id]/checkout-qr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/properties/[id]/checkout-qr">> = Specific
  const handler = {} as typeof import("../../app/admin/properties/[id]/checkout-qr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/properties/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/properties/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/properties/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/properties/[id]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/properties/[id]/settings">> = Specific
  const handler = {} as typeof import("../../app/admin/properties/[id]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/properties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/properties">> = Specific
  const handler = {} as typeof import("../../app/admin/properties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/seed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/seed">> = Specific
  const handler = {} as typeof import("../../app/admin/seed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/profile">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/staff">> = Specific
  const handler = {} as typeof import("../../app/admin/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/supplies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/supplies">> = Specific
  const handler = {} as typeof import("../../app/admin/supplies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tour-bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tour-bookings">> = Specific
  const handler = {} as typeof import("../../app/admin/tour-bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tour-operators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tour-operators">> = Specific
  const handler = {} as typeof import("../../app/admin/tour-operators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tours/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tours/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/tours/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tours/[id]/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tours/[id]/schedule">> = Specific
  const handler = {} as typeof import("../../app/admin/tours/[id]/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tours">> = Specific
  const handler = {} as typeof import("../../app/admin/tours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api-docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-docs">> = Specific
  const handler = {} as typeof import("../../app/api-docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/c/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/c/[token]">> = Specific
  const handler = {} as typeof import("../../app/c/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cleaner/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cleaner/calendar">> = Specific
  const handler = {} as typeof import("../../app/cleaner/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cleaner/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cleaner/history">> = Specific
  const handler = {} as typeof import("../../app/cleaner/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cleaner/issues/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cleaner/issues">> = Specific
  const handler = {} as typeof import("../../app/cleaner/issues/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cleaner/laundry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cleaner/laundry">> = Specific
  const handler = {} as typeof import("../../app/cleaner/laundry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cleaner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cleaner">> = Specific
  const handler = {} as typeof import("../../app/cleaner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cleaner/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cleaner/schedule">> = Specific
  const handler = {} as typeof import("../../app/cleaner/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cleaner/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cleaner/settings">> = Specific
  const handler = {} as typeof import("../../app/cleaner/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cleaner/supplies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cleaner/supplies">> = Specific
  const handler = {} as typeof import("../../app/cleaner/supplies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/guest-checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest-checkout">> = Specific
  const handler = {} as typeof import("../../app/guest-checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/guest/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest/[slug]">> = Specific
  const handler = {} as typeof import("../../app/guest/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/guest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guest">> = Specific
  const handler = {} as typeof import("../../app/guest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[token]">> = Specific
  const handler = {} as typeof import("../../app/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup">> = Specific
  const handler = {} as typeof import("../../app/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/api-clients/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/api-clients/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/api-clients/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/api-clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/api-clients">> = Specific
  const handler = {} as typeof import("../../app/api/admin/api-clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bookings">> = Specific
  const handler = {} as typeof import("../../app/api/admin/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/calendar/events/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/calendar/events/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/calendar/events/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/calendar">> = Specific
  const handler = {} as typeof import("../../app/api/admin/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/calendar/supply-todos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/calendar/supply-todos">> = Specific
  const handler = {} as typeof import("../../app/api/admin/calendar/supply-todos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/notify-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/notify-test">> = Specific
  const handler = {} as typeof import("../../app/api/admin/notify-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payments">> = Specific
  const handler = {} as typeof import("../../app/api/admin/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beds24/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beds24/bookings">> = Specific
  const handler = {} as typeof import("../../app/api/beds24/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beds24/maintenance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beds24/maintenance">> = Specific
  const handler = {} as typeof import("../../app/api/beds24/maintenance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beds24/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beds24/messages">> = Specific
  const handler = {} as typeof import("../../app/api/beds24/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beds24/messages/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beds24/messages/send">> = Specific
  const handler = {} as typeof import("../../app/api/beds24/messages/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beds24/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beds24/reservations">> = Specific
  const handler = {} as typeof import("../../app/api/beds24/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beds24/sync-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beds24/sync-all">> = Specific
  const handler = {} as typeof import("../../app/api/beds24/sync-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/beds24/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beds24/sync">> = Specific
  const handler = {} as typeof import("../../app/api/beds24/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bookings/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/cancel">> = Specific
  const handler = {} as typeof import("../../app/api/bookings/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings">> = Specific
  const handler = {} as typeof import("../../app/api/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/camera/diagnostics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/camera/diagnostics">> = Specific
  const handler = {} as typeof import("../../app/api/camera/diagnostics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/camera/snapshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/camera/snapshots">> = Specific
  const handler = {} as typeof import("../../app/api/camera/snapshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/checkout/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/confirm">> = Specific
  const handler = {} as typeof import("../../app/api/checkout/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/checkout/qr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/qr">> = Specific
  const handler = {} as typeof import("../../app/api/checkout/qr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cleaner/today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cleaner/today">> = Specific
  const handler = {} as typeof import("../../app/api/cleaner/today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cleaners/[id]/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cleaners/[id]/invite">> = Specific
  const handler = {} as typeof import("../../app/api/cleaners/[id]/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cleaners/[id]/properties/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cleaners/[id]/properties">> = Specific
  const handler = {} as typeof import("../../app/api/cleaners/[id]/properties/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cleaners/[id]/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cleaners/[id]/reset-password">> = Specific
  const handler = {} as typeof import("../../app/api/cleaners/[id]/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cleaners/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cleaners/me">> = Specific
  const handler = {} as typeof import("../../app/api/cleaners/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cleaners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cleaners">> = Specific
  const handler = {} as typeof import("../../app/api/cleaners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cleaning-applications/[id]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cleaning-applications/[id]/approve">> = Specific
  const handler = {} as typeof import("../../app/api/cleaning-applications/[id]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cleaning-applications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cleaning-applications">> = Specific
  const handler = {} as typeof import("../../app/api/cleaning-applications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cleaning-issues/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cleaning-issues">> = Specific
  const handler = {} as typeof import("../../app/api/cleaning-issues/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cleanings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cleanings">> = Specific
  const handler = {} as typeof import("../../app/api/cleanings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/[id]/automation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations/[id]/automation">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/[id]/automation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/camera-inbox/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/camera-inbox">> = Specific
  const handler = {} as typeof import("../../app/api/cron/camera-inbox/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/payments">> = Specific
  const handler = {} as typeof import("../../app/api/cron/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/debug/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/me">> = Specific
  const handler = {} as typeof import("../../app/api/debug/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events">> = Specific
  const handler = {} as typeof import("../../app/api/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/export/[channelId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/export/[channelId]">> = Specific
  const handler = {} as typeof import("../../app/api/export/[channelId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guest-services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guest-services">> = Specific
  const handler = {} as typeof import("../../app/api/guest-services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guests/directory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guests/directory">> = Specific
  const handler = {} as typeof import("../../app/api/guests/directory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guests/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guests/history">> = Specific
  const handler = {} as typeof import("../../app/api/guests/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guests">> = Specific
  const handler = {} as typeof import("../../app/api/guests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/holidays/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/holidays">> = Specific
  const handler = {} as typeof import("../../app/api/holidays/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inquiry-automation/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inquiry-automation/process">> = Specific
  const handler = {} as typeof import("../../app/api/inquiry-automation/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/invitations/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invitations/[token]">> = Specific
  const handler = {} as typeof import("../../app/api/invitations/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/invitations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invitations">> = Specific
  const handler = {} as typeof import("../../app/api/invitations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/laundry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/laundry">> = Specific
  const handler = {} as typeof import("../../app/api/laundry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/unread-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/unread-count">> = Specific
  const handler = {} as typeof import("../../app/api/messages/unread-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ops/today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ops/today">> = Specific
  const handler = {} as typeof import("../../app/api/ops/today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/properties/[id]/channels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/properties/[id]/channels">> = Specific
  const handler = {} as typeof import("../../app/api/properties/[id]/channels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/properties/[id]/inquiry-automation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/properties/[id]/inquiry-automation">> = Specific
  const handler = {} as typeof import("../../app/api/properties/[id]/inquiry-automation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/properties/[id]/inquiry-notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/properties/[id]/inquiry-notifications">> = Specific
  const handler = {} as typeof import("../../app/api/properties/[id]/inquiry-notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/properties/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/properties/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/properties/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/properties/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/properties">> = Specific
  const handler = {} as typeof import("../../app/api/properties/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/bookings">> = Specific
  const handler = {} as typeof import("../../app/api/public/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/checkout/paypal/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/checkout/paypal/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/public/checkout/paypal/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/public/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/checkout/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/checkout/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/public/checkout/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/guest-checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/guest-checkout">> = Specific
  const handler = {} as typeof import("../../app/api/public/guest-checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/guest-services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/guest-services">> = Specific
  const handler = {} as typeof import("../../app/api/public/guest-services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/properties/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/properties/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/public/properties/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/properties/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/properties">> = Specific
  const handler = {} as typeof import("../../app/api/public/properties/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/stay-calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/stay-calendar">> = Specific
  const handler = {} as typeof import("../../app/api/public/stay-calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/stay-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/stay-search">> = Specific
  const handler = {} as typeof import("../../app/api/public/stay-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/tour-bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/tour-bookings">> = Specific
  const handler = {} as typeof import("../../app/api/public/tour-bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/tours/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/tours/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/public/tours/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/tours/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/tours">> = Specific
  const handler = {} as typeof import("../../app/api/public/tours/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/welcomepad/active-event-override/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/welcomepad/active-event-override">> = Specific
  const handler = {} as typeof import("../../app/api/public/welcomepad/active-event-override/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/welcomepad/checkins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/welcomepad/checkins">> = Specific
  const handler = {} as typeof import("../../app/api/public/welcomepad/checkins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/welcomepad/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/welcomepad/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/public/welcomepad/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/public/welcomepad/cleanings/done/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/welcomepad/cleanings/done">> = Specific
  const handler = {} as typeof import("../../app/api/public/welcomepad/cleanings/done/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup">> = Specific
  const handler = {} as typeof import("../../app/api/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/cleaning-role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/cleaning-role">> = Specific
  const handler = {} as typeof import("../../app/api/staff/cleaning-role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/link">> = Specific
  const handler = {} as typeof import("../../app/api/staff/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff/merge">> = Specific
  const handler = {} as typeof import("../../app/api/staff/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/staff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/staff">> = Specific
  const handler = {} as typeof import("../../app/api/staff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/supply-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/supply-requests">> = Specific
  const handler = {} as typeof import("../../app/api/supply-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/supply-todos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/supply-todos">> = Specific
  const handler = {} as typeof import("../../app/api/supply-todos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync">> = Specific
  const handler = {} as typeof import("../../app/api/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tour-bookings/[id]/forward/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tour-bookings/[id]/forward">> = Specific
  const handler = {} as typeof import("../../app/api/tour-bookings/[id]/forward/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tour-bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tour-bookings">> = Specific
  const handler = {} as typeof import("../../app/api/tour-bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tour-dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tour-dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/tour-dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tour-operators/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tour-operators">> = Specific
  const handler = {} as typeof import("../../app/api/tour-operators/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tours/[id]/duration-options/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tours/[id]/duration-options">> = Specific
  const handler = {} as typeof import("../../app/api/tours/[id]/duration-options/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tours/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tours/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/tours/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tours/[id]/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tours/[id]/schedule">> = Specific
  const handler = {} as typeof import("../../app/api/tours/[id]/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tours/[id]/ticket-tiers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tours/[id]/ticket-tiers">> = Specific
  const handler = {} as typeof import("../../app/api/tours/[id]/ticket-tiers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tours/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tours">> = Specific
  const handler = {} as typeof import("../../app/api/tours/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/uploads/tour-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads/tour-image">> = Specific
  const handler = {} as typeof import("../../app/api/uploads/tour-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/bookings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/v1/bookings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/bookings">> = Specific
  const handler = {} as typeof import("../../app/api/v1/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/cleanings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/cleanings/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/v1/cleanings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/cleanings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/cleanings">> = Specific
  const handler = {} as typeof import("../../app/api/v1/cleanings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/properties/[id]/availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/properties/[id]/availability">> = Specific
  const handler = {} as typeof import("../../app/api/v1/properties/[id]/availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/properties/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/properties">> = Specific
  const handler = {} as typeof import("../../app/api/v1/properties/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/welcomepad-chat/mark-read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/welcomepad-chat/mark-read">> = Specific
  const handler = {} as typeof import("../../app/api/welcomepad-chat/mark-read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/welcomepad-chat/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/welcomepad-chat/messages">> = Specific
  const handler = {} as typeof import("../../app/api/welcomepad-chat/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/welcomepad-chat/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/welcomepad-chat/threads">> = Specific
  const handler = {} as typeof import("../../app/api/welcomepad-chat/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/c/[token]/ical.ics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/c/[token]/ical.ics">> = Specific
  const handler = {} as typeof import("../../app/c/[token]/ical.ics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ical/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ical/[slug]">> = Specific
  const handler = {} as typeof import("../../app/ical/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cleaner/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cleaner">> = Specific
  const handler = {} as typeof import("../../app/cleaner/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
